### ISSUE TITLE
Недоработки и баги слайдера.

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/Slider#1]
1. Давай, все таки, семантически сгруппируем min/max, что бы они шли рядом. Объчно все так делают и это скорее просьба чем претензия. 
![slider](https://user-images.githubusercontent.com/75975369/109927269-fdecd600-7cd4-11eb-8332-bd710ac0b351.jpg)

**Comment by mglknFSD** [comment]
2. Баг. При попытке установить max почему-то меняется шаг и "едет" верстка слайдера.

https://user-images.githubusercontent.com/75975369/109929274-56bd6e00-7cd7-11eb-8fb9-91d058779d74.mp4

**Comment by mglknFSD** [comment]
3. Слайдер "застревает", не доходит до своего крайнего положения.


https://user-images.githubusercontent.com/75975369/109929604-b7e54180-7cd7-11eb-883a-ba91e09489ef.mp4

**Comment by mglknFSD** [comment]
4. Необходимо сделать что бы бегунки слайдера можно было перемещать не только за "точки", но и за "тултипы" (значения над точками).

**Comment by igorpichnenko** [comment]
Сгруппировал мин/Макс, убрал баг с изменением максимального значения, у меня from не корректировался в этот момент, а шаг у меня изменяется потому что стоит корректировка что шаг может быть не больше 50% от разницы между макс и мин, если хотите то уберу корректировку..

**Comment by igorpichnenko** [comment]
Насчёт 3 пункта я постараюсь сделать, но там так много слушателей, для сенсора, кликов, мышки, Custom Event и я всё это настраивал, и если водить бегунки с нормальной скоростью плавно то все вроде выглядит нормально..


По поводу 4 пункта уточните что имеете ввиду? Не понятно, я перечитал 8 пунктов ТЗ к проекту и там нет таких требований, точнее я даже не понял что должно быть по итогу

**Comment by igorpichnenko** [comment]
По поводу 3 пункта, пришлось перебрать полностью весь проект пару раз, но я устранил зависание, теперь действительно прям нравится как работает)

Uploading Screenrecorder-2021-03-04-23-47-37-203.mp4…

**Comment by mglknFSD** [comment]
> 
> 
> По поводу 3 пункта, пришлось перебрать полностью весь проект пару раз, но я устранил зависание, теперь действительно прям нравится как работает)
> 
> Uploading Screenrecorder-2021-03-04-23-47-37-203.mp4…

Так держать!

**Comment by mglknFSD** [comment]
5. По условию задания шаг может быть любым.

В первом случае он назначается сам исходя из какой-то внутренне логики.

https://user-images.githubusercontent.com/75975369/110235463-237e1780-7f41-11eb-890e-c608d7030548.mp4

А тут я не могу задать шаг меньше 1.

https://user-images.githubusercontent.com/75975369/110235465-2416ae00-7f41-11eb-8ce6-8c22038ce725.mp4

**Comment by mglknFSD** [comment]
> По поводу 4 пункта уточните что имеете ввиду? Не понятно, я перечитал 8 пунктов ТЗ к проекту и там нет таких требований, точнее я даже не понял что должно быть по итогу

Тултип - это цифры значения сверху ползунка.
Это логичное требование, точка маленькая в нее бывает сложно попасть, тултип, если он отображается, должен этому способствовать. Так что в полне логично что если тултип есть, за него можно потянуть как за бегунок.

**Comment by mglknFSD** [comment]
Баги слайдера.

https://user-images.githubusercontent.com/75975369/111861958-19a5dc80-8963-11eb-8ed6-d7e9698b43fe.mov

https://user-images.githubusercontent.com/75975369/111861960-1ca0cd00-8963-11eb-9325-041288485449.mov

**Comment by mglknFSD** [comment]
Так же нет элементов управления скрыть/показать тултип.

**Comment by igorpichnenko** [comment]
А точка это бегунок выходит, тогда понял, добавил перетягивание за тултип, и переключение

**Comment by mglknFSD** [comment]
Баг шкалы не исправлен

https://user-images.githubusercontent.com/75975369/112744991-93664780-8fad-11eb-851c-566d28597f6a.mp4

**Comment by mglknFSD** [comment]
Еще баг шкалы

https://user-images.githubusercontent.com/75975369/113511020-65ad6f80-9566-11eb-8d10-4c0a8e4b91ae.mp4

**Comment by mglknFSD** [comment]
Большая "точка" может "двигать" меньшую. Такого быть не должно.

https://user-images.githubusercontent.com/75975369/113511092-ca68ca00-9566-11eb-8b3c-172d90cc7ba4.mp4
