### ISSUE TITLE
ts

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/Slider#3]
Кондишены содержащие больше одного условия должны быть вынесены.

![if](https://user-images.githubusercontent.com/75975369/112745161-0a501000-8faf-11eb-9538-0c29c2ac21a5.jpg)

**Comment by mglknFSD** [comment]
Очень большой интерфейс. Его лучше распилить на маленькие, и собрать в большой через `extends`.

![interface](https://user-images.githubusercontent.com/75975369/112745183-3d929f00-8faf-11eb-8eeb-cfe8e5e1ddd2.jpg)

**Comment by mglknFSD** [comment]
Поисковые слелекторы должны быть с js- префиксом

![js](https://user-images.githubusercontent.com/75975369/112745240-8d716600-8faf-11eb-9903-a602a811e994.jpg)

**Comment by mglknFSD** [comment]
Вложеных if-ов лучше избегать. Такой код тяжело поддерживать. 

![nested if](https://user-images.githubusercontent.com/75975369/112745289-db866980-8faf-11eb-9b80-66cd08c7fc02.jpg)

Такое можно переписать так

```ts
if (from > 0 && isMinMaxZero) {
  options.from = min;
}
```

... ну и двойной кондишен вынести в отдельную функцию.
Ну и этот и другие issues смотри по всему проекту.

**Comment by mglknFSD** [comment]
Лучше не полагаться на строки при таких сравнениях (в них легко допустить ошибку, которую будет сложно отловить). Для конечного набора значений используются `enum`. 

![enum](https://user-images.githubusercontent.com/75975369/112745533-d4f8f180-8fb1-11eb-9282-d391c764e89d.jpg)

**Comment by mglknFSD** [comment]
`Orientation[1]` я не очень понимаю, это ты так к свойству enum-а пытаешься обратится? Так никто не делает, исправь пожалуйста.

![enum](https://user-images.githubusercontent.com/75975369/113511564-043ad000-9569-11eb-97fe-d6091fb5fbb9.jpg)

**Comment by mglknFSD** [comment]
![many arguments](https://user-images.githubusercontent.com/75975369/113511969-246b8e80-956b-11eb-8148-b796cad4722c.jpg)

Для функции принимающей боьльшое количество аргументов (3 и больше), аргументы лучше передавать в виде объекта ( что бы не перепутать порядок аргументов и не передать, например, `position` вместо `value`) и при получении использовать деструктуризацию. 

Для примера

```ts
const someFn = ({ a, b, c }: { a: number, b: string, c: number }) => { ... }

someFn({a: 1, b: 'Hello', c: 2,});
```

**Comment by mglknFSD** [comment]
Все имена классов необходимо выносить в переменные. А еще лучше создать единый конфиг и импортировать его.

![strings](https://user-images.githubusercontent.com/75975369/113512309-b7f18f00-956c-11eb-9f08-ebe896f5f309.jpg)

**Comment by igorpichnenko** [comment]
Исправил

**Comment by mglknFSD** [comment]
Тут и в других местах. В предикатных выражениях нет необходимости делать явное сравнение с булевыми значениями - они и так либо true либо false

![equality](https://user-images.githubusercontent.com/75975369/114205247-c53ebd00-9962-11eb-95de-9e4a4a418864.jpg)

**Comment by mglknFSD** [comment]
Где возможно,  необходимо использовать деструктуризацию.

```typescipt
const [someVall, anotherSomeVal] = [1,2];
```

![destructuring](https://user-images.githubusercontent.com/75975369/114204903-64af8000-9962-11eb-8857-6086ea9f49ae.jpg)

**Comment by mglknFSD** [comment]
Тут и в других местах. Все классы выносим в переменные. 

![var](https://user-images.githubusercontent.com/75975369/114205559-13ec5700-9963-11eb-9bef-a66d05e4e14e.jpg)

**Comment by mglknFSD** [comment]
Тут и в других местах. Деструктуризацию в таких случаях лучше применять прямо в аргументах функции.

```typescript
  public getNewSliderPos({ slider, isVertical }: IViewState): number {
    let position = 0;

    if (!isVertical) {
      position = slider.getBoundingClientRect().left;
    } else {
      position = slider.getBoundingClientRect().top;
    }
    return position;
  }
}

```

![destructuring](https://user-images.githubusercontent.com/75975369/114205739-4e55f400-9963-11eb-82b0-1fd596a38a14.jpg)

**Comment by mglknFSD** [comment]
RegExp объекты лучше объявлять снаружи

![rx](https://user-images.githubusercontent.com/75975369/114207787-70e90c80-9965-11eb-8d78-982349289739.jpg)

**Comment by mglknFSD** [comment]
Такие вещи лучше из строк выносить в `enum`. И давать более идиоматические названия. (в данном случае я бы enum назвал Direction а значение FORWARD, BACKWARD)

![enum](https://user-images.githubusercontent.com/75975369/114211183-fde19500-9968-11eb-99b4-3fe17e1f643d.jpg)

**Comment by mglknFSD** [comment]
Аналогично названия эвентов хранить в строках - плохая практика, сделай через enum.

![events](https://user-images.githubusercontent.com/75975369/114211460-57e25a80-9969-11eb-97be-b86826d7b4a8.jpg)

**Comment by igorpichnenko** [comment]
Исправил. Поводу того примера где from, to, там у меня 2 разных проверки в одном методе, и уже как минимум надо тогда 4 разных значения enum использовать. В bar у меня тоже есть подобная проверка, выходит что и там тогда нужно использовать enum Direction, выходит 8 значений тогда, я понимаю плюс этого подхода, но пока сложности с названием этих значений.. эвэнты тоже вынес в отдельный enum, но эвэнты которые относятся к ванильному js я не трогал, типо mouseup

**Comment by mglknFSD** [comment]
> 
> 
> Исправил. Поводу того примера где from, to, там у меня 2 разных проверки в одном методе, и уже как минимум надо тогда 4 разных значения enum использовать. эвэнты тоже вынес в отдельный enum, но эвэнты которые относятся к ванильному js я не трогал, типо mouseup

Ну к ванильному и не надо.

**Comment by mglknFSD** [comment]
1) Смысл выносить создание объектов на топ уровень - оптимизационный (для того что бы они не создавались при каждом вызове функции. )
2) Крайне плохое имя для переменной regexp.

![regexp](https://user-images.githubusercontent.com/75975369/114313448-3c10bd00-9aff-11eb-9910-97b258c6676d.jpg)

**Comment by mglknFSD** [comment]
Зачем ты из enum-ов десструктуризацию делаешь? Не надо так.

![enum](https://user-images.githubusercontent.com/75975369/114313688-2ea80280-9b00-11eb-8020-6539677decfb.jpg)

**Comment by mglknFSD** [comment]
Вот это совершенно бессмысленный код.

![noncence](https://user-images.githubusercontent.com/75975369/114313770-86df0480-9b00-11eb-81f1-88d24c7c79d5.jpg)

Ок, я тут погорячился заставив тебя применить деструкрутуризацию (.querySelectorAll возвращает не массив), но можно было мне на это указать, или написать хотя бы так

```typescript
const [rollerFirst, rollerSecond] = Array.from(this.slider.querySelectorAll(classNames.findRollers));
```

**Comment by mglknFSD** [comment]
Тут тоже очень уместен destructuring.

![pos](https://user-images.githubusercontent.com/75975369/114313962-65cae380-9b01-11eb-9db5-6d992e071a25.jpg)

**Comment by mglknFSD** [comment]
Если тебе что-то не понятно, не бойся спрашивать.

**Comment by igorpichnenko** [comment]
1 Смысл выносить создание объектов на топ уровень - оптимизационный (для того что бы они не создавались при каждом вызове функции. )

Это я не понял, слишком размыто, можно подробнее что вы имеете ввиду?

**Comment by igorpichnenko** [comment]
Исправил деструктизацию, есть 2 вопроса
1) Почему не используют деструктизацию enum? Где об этом написано что это плохо и к чему это может привести?
2) почему к enum нельзя обращаться через orientation[0] например, чем это плохо? Это не читаемо или нагружает процессор?

**Comment by mglknFSD** [comment]
> 
> 
> Исправил деструктизацию, есть 2 вопроса
> 
>     1. Почему не используют деструктизацию enum? Где об этом написано что это плохо и к чему это может привести?
> 
>     2. почему к enum нельзя обращаться через orientation[0] например, чем это плохо? Это не читаемо или нагружает процессор?

1 Деструктуризация используется для того что бы выделить в переменную нужный нам объект из некоторого контейнера что бы не засорять пространство имен, либо, что бы не ссылаться лишний раз на контейнер с целью повышения читаемости кода. Ключевое тут, что у нас есть контейнер и есть нужный нам объект и они друг с другом связаны опосредованно. В случае enum - это просто контейнер для объектов значения которых нам не интересны. Ничего, кроме как сравнения с переменными такого же типа того же контейнера с ними делать ничего не следует. Поэтому вне этого контейнера эти объекты не мыслятся, и деструктурировать их в переменные (и засорять локальное пространство имен) никакого смысла не имеет.

2. Ну вот как это читать `orientation[0]`? Я должен заучивать порядок ориентации в enum orientation, а затем при чтении кода вспоминать что там стоит на 1-м месте? (Кстати, имена типов следует писать с заглавной буквы). Почему нельзя написать `orientation.BACKWARD`? Зачем это городить? Я искренне не понимаю в чем проблема?

**Comment by mglknFSD** [comment]
> 
> 
>     1. как тогда назвать regexp? Мне кажется называть все своими именами не плохая идея, человеку сразу понятно для чего эта переменная..
>        Я могу назвать re например

Ну вот ты собираешься назвать его re, а если их 2 будет или 10? Ты их будешь re1, re2, re3 называть? И о чем читающему твой код будут говорить эти названия? Да ни о чем...

Ну наверное следует исходить из семантики того чему ты собираешься дать имя. Ты делаешь проверку на вхождение подстроки `scale`, ну логичный вариант может выглядеть так `checkScaleRgx`.

P.S. для проверки подстроки у `string` есть метод `.contain()`. Регулярное выражение тут вообще не нужно

**Comment by igorpichnenko** [comment]
Теперь понятно.
Насчёт contain я понимаю, я просто пока учился пробовал по разному, и проверка с regexp выходила короче, сегодня переписал проверки на выриант с contain()
