### ISSUE TITLE
Demo страница.

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/Slider#5]
1) Demo page template. Так лучше не писать. Если у тебя подключен pug - используй его. Распили на компоненты где каждый блок это отдельный слайдер. 

![html](https://user-images.githubusercontent.com/75975369/114312813-a7a55b00-9afc-11eb-8d93-856a9f71a655.jpg)

2) Функция на 338 строк!!!!!! Немедленно распилить
![fn](https://user-images.githubusercontent.com/75975369/114313058-9e68be00-9afd-11eb-8187-0ac7fc7296d3.jpg)

**Comment by igorpichnenko** [comment]
Отрефакторил до 30 строк
